
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://123.207.61.161:3306/yybun
    username: root
    password: 0221liurl
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


